/**
 * A queue row addresses ONE variant, not one post.
 *
 * A post with a Facebook and an Instagram variant is two rows, two captions and
 * two previews, so the id is the CMS document id, then `__`, then the variant
 * key: `drafts.post-8f21__ig`. The document id contains a dot, which is why the
 * store routes around Rails' format parsing to carry it.
 *
 * Split on the LAST `__`, because a Sanity document id may contain `__` itself
 * but a variant key generated by the Studio will not.
 */

const SEPARATOR = '__'

export function variantId(documentId, variantKey) {
  if (!documentId || !variantKey) return null
  return `${documentId}${SEPARATOR}${variantKey}`
}

export function splitVariantId(id) {
  if (typeof id !== 'string') return null
  const at = id.lastIndexOf(SEPARATOR)
  if (at <= 0 || at + SEPARATOR.length >= id.length) return null
  return {
    documentId: id.slice(0, at),
    variantKey: id.slice(at + SEPARATOR.length),
  }
}

/** `drafts.abc` and `abc` are the same post; this is the published one. */
export function publishedId(documentId) {
  return String(documentId ?? '').replace(/^drafts\./, '')
}

export function isDraftId(documentId) {
  return String(documentId ?? '').startsWith('drafts.')
}
